---
image: dockerep-0.mtl.mnubo.com/toolbox-frontend:latest

include:
  - remote: "https://git-lab1.mtl.mnubo.com/ops/gitlab-ci-templates/raw/master/variables-sbt.yml"
  - remote: "https://git-lab1.mtl.mnubo.com/ops/gitlab-ci-templates/raw/master/cache-dataviz.yml"
  - remote: "https://git-lab1.mtl.mnubo.com/ops/gitlab-ci-templates/raw/master/before-script-dataviz.yml"
  - remote: "https://git-lab1.mtl.mnubo.com/ops/gitlab-ci-templates/raw/master/dataviz-job-templates.yml"

stages:
  - project
  - publish

project:rebase:
  stage: project
  variables:
    VERSION: "1.0.${CI_PIPELINE_IID}"
  only:
    - master@dataviz/scala-steward
  tags:
    - us3
    - dind
  script:
    - env
    - git remote -vvv
    - ./mnubo/rebase.sh
  when: manual

publish:
  stage: publish
  only:
    - tags
  tags:
    - us3
    - dind
  script:
    - ./mnubo/build.sh
